pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
    plugins {
        id "com.diffplug.spotless" version "${spotlessVersion}"
        id "com.gradleup.shadow" version "${shadowJarVersion}"
    }
}

rootProject.name = "lh-kafka-connect"
include "connector"
include "examples-common"

new File(rootProject.projectDir, "examples").eachDir { dir ->
    if (new File(dir, "build.gradle").exists()) {
        include "example-${dir.name}"
        project(":example-${dir.name}").projectDir = dir
    }
}
