// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: species.proto
// Protobuf Java Version: 4.29.3

package io.littlehorse.example;

public interface SpeciesOrBuilder
        extends
        // @@protoc_insertion_point(interface_extends:Species)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString getNameBytes();
}
